In [1]:
import pandas as pd
import sys
sys.path.append('../src')
import model_training_functions_australia

In [4]:
australia_bac_dataset = pd.read_csv('../data/processed/australia_bac_dataset_processed.csv')
australia_bac_dataset

    Bodyweight_grams  Height  Age  1hr-BAC  Ethanol_grams  Gender_male
0            31752.0     167   20    0.025          37.88            0
1            29937.6     161   21    0.040          37.88            0
2            30391.2     169   27    0.070          56.82            1
3            41277.6     187   20    0.065          56.82            1
4            26308.8     158   25    0.015          28.41            0
5            36288.0     177   29    0.020          28.41            1
6            28576.8     162   26    0.000           9.47            0
7            34020.0     170   48    0.015          28.41            1
8            56246.4     184   22    0.000          28.41            1
9            40824.0     171   50    0.020          28.41            1
10           36288.0     179   39    0.030          37.88            1
11           41277.6     183   32    0.065          47.35            1
12           23587.2     159   22    0.040          18.94            0
13           41277.6     187   22    0.035          56.82            1
14           48535.2     185   24    0.045          66.29            1
15           34020.0     180   45    0.080          37.88            1
16           38556.0     178   46    0.010          18.94            1
17           45813.6     181   27    0.045          85.23            1
18           24948.0     164   18    0.130          56.82            0
19           36288.0     179   18    0.085          66.29            1
20           27216.0     158   30    0.020          28.41            0
21           31752.0     151   44    0.105          56.82            0

In [5]:
model_training_functions_australia.results(australia_bac_dataset, ['Ethanol_grams'], '1hr-BAC')

Features: ['Ethanol_grams']
Target: 1hr-BAC
Mean Squared Error: 0.0006883659110181468
R2 score: -0.021314408038793475

In [6]:
model_training_functions_australia.results(australia_bac_dataset, ['Ethanol_grams', 'Gender_male'], '1hr-BAC')

Features: ['Ethanol_grams', 'Gender_male']
Target: 1hr-BAC
Mean Squared Error: 0.0009375842473651735
R2 score: -0.39107455098690425

In [7]:
model_training_functions_australia.results(australia_bac_dataset, ['Ethanol_grams', 'Bodyweight_grams'], '1hr-BAC')

Features: ['Ethanol_grams', 'Bodyweight_grams']
Target: 1hr-BAC
Mean Squared Error: 0.0007208494333845469
R2 score: -0.06950954508092999

In [6]:
model_training_functions_australia.results(australia_bac_dataset, ['Ethanol_grams', 'Bodyweight_grams', 'Age', 'Gender_male'], '1hr-BAC')

Features: ['Ethanol_grams', 'Bodyweight_grams', 'Age', 'Gender_male']
Target: 1hr-BAC
Mean Squared Error: 0.0007367456198391379
R2 score: -0.09309439145272691